<?php
// src/Model/Table/UsersTable.php
namespace App\Model\Table;

use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\ORM\RulesChecker;  //як варіант для унікальності імен
use Cake\ORM\Rule\IsUnique;


class UsersTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->hasMany('Articles', [
            'foreignKey' => 'user_id',
        ]);
        $this->setTable('users');
        $this->setPrimaryKey('id');

    }


    public function validationDefault(Validator $validator)
    {

        return $validator
            ->notEmpty('name', 'A username is required')
            ->notEmpty('email', 'A username is required')
            ->notEmpty('password', 'A password is required');
    }



    // як варіант для унікальності
    //включити шоб унікальна пошта була і імя


//    public function buildRules(RulesChecker $rules)
//    {
//        $rules->add($rules->isUnique(['email'], 'email already exist.'));
//        $rules->add($rules->isUnique(['name'], 'name already exist.'));
//
//        return $rules;
//    }


}
